source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

link_with 'ImageManager', 'ImageManager_Tests'

target 'ImageManager_Tests', :exclusive => true do
  pod "ImageManager", :path => "../"
  pod "OCMock"
  pod "PromiseKit/Promise", "~> 1.6"
end
